# Generated by Django 5.2.1 on 2025-05-21 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cause",
            fields=[
                ("cause_id", models.AutoField(primary_key=True, serialize=False)),
                ("primary_cause", models.CharField(max_length=255)),
                (
                    "secondary_cause",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisasterType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=100)),
                ("response_time", models.IntegerField()),
                ("frequency", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("area", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Severity",
            fields=[
                ("severity_id", models.AutoField(primary_key=True, serialize=False)),
                ("level", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Disaster",
            fields=[
                ("disaster_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("confirmation", models.BooleanField(default=False)),
                ("duration", models.IntegerField()),
                (
                    "cause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cause"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.disastertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Impact",
            fields=[
                ("impact_id", models.AutoField(primary_key=True, serialize=False)),
                ("evacuated", models.IntegerField()),
                ("injured", models.IntegerField()),
                ("death", models.IntegerField()),
                ("ecology", models.CharField(max_length=255)),
                (
                    "disaster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.disaster"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisasterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disaster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.disaster"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.location"
                    ),
                ),
            ],
            options={
                "unique_together": {("disaster", "location")},
            },
        ),
        migrations.AddField(
            model_name="disaster",
            name="locations",
            field=models.ManyToManyField(
                through="core.DisasterLocation", to="core.location"
            ),
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.location"
                    ),
                ),
            ],
            options={
                "unique_together": {("location", "name")},
            },
        ),
        migrations.CreateModel(
            name="Aid",
            fields=[
                ("aid_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "disaster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.disaster"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryShelter",
            fields=[
                ("shelter_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("area", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("capacity", models.IntegerField()),
                (
                    "disaster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.disaster"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.location"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="disaster",
            name="severity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.severity"
            ),
        ),
    ]
